name: TestMavenOrGradle

on: [push]

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: | 
          cd libcobj
          mvn --batch-mode --update-snapshots package
  
  gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change directory
        run: cd libcobj
      
      - name: Build with Gradle
        uses: ./gradlew build

      - name: Change directory again
        run: cd ..