name: TestMavenOrGradle

on: [push]

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: apt update -y

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
  
  gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: apt update -y

      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        run: ./gradlew build