name: TestMavenOrGradle

on: [push]

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: | 
          cd libcobj
          mvn --batch-mode --update-snapshots package
  
  gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

    - name: restore gradle cache
      uses: actions/cache@v2
      with:
        path: |
          /root/.gradle/caches
          /root/.gradle/wrapper

      - name: Change directory
        run: cd libcobj
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Change directory again
        run: cd ..