name: TestMavenOrGradle

on: [push]

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: | 
          cd libcobj
          ls
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          cd ..
  
  gradle-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd libcobj
          ls
          gradle build --scan
          cd ..