name: TestMavenOrGradle

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  maven-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:

      - name: Install
        run: |
          apt update -y
          apt install -y default-jdk maven

      - name: Checkout 
        uses: actions/checkout@v3

      - name: Make sample project
        run: |
          mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
      
      - name: Package sample project
        run: |
          cd my-app
          mvn package
          ls target
      
      - name: Run sample project
        run: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
  
  gradle-test: 
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:

      - name: Install JDK
        run: |
          apt update -y
          apt install -y default-jdk
      
      - name: Install gradle
        run: |
          wget -P temp https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
          unzip -d /opt/gradle temp/gradle-8.0.2-bin.zip
          ls /opt/gradle/gradle-8.0.2
      
      - name: Set PATH
        run: export PATH=$PATH:/opt/gradle/gradle-8.0.2/bin

      - name: Check version
        run: gradle -v