name: test

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:

      - name: Install
        run: |
          apt update -y
          apt install -y default-jdk maven

      - name: Make sample project
        run: |
          mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
      
      - name: Compile sample project
        run: mvn compile
      
      - name: Run sample project
        run: mvn exec:java -Dexec.mainClass=com.mycompany.app.App