name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: |
          apt update
          apt install -y default-jdk maven

      - name: til package sample project
        run: |
          mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
          mvn package
      
      - name: Run sample project
        run: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App